### ISSUE TITLE
How to get lidar pose

### ISSUE THREAD

**Issue by Miyeap** [Toytiny/RadarOcc#3]
Hello! In process_kradar.py, it needs "lidar_ego_pose0.npy" as lidar pose to process. Could you share how to get it or maybe the complete pose files?

**Comment by Ericwen2001** [comment]
Apologies for not including this in the instructions. As mentioned in our paper, we used KISS-ICP to generate LiDAR poses, as we found the ground truth poses provided by K-Radar to be unreliable, particularly in terms of height. I recommend trying it out yourself, and I’ll try locating our script and uploading it.

**Comment by Miyeap** [comment]
Thanks for your help!
